src/SME_UnB/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^transductor/', include('transductor.urls',
                                  namespace="transductor")),
    url(r'^accounts/', include('users.urls', namespace="users")),
    url(r'^reports/', include('report.urls', namespace="report")),
    url(r'^retrieve_password/', include('retrieve_password.urls', namespace="retrieve")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

src/report/urls.py
from django.conf.urls import url

from . import views

app_name = 'report'
urlpatterns = [
    url(r'^report/(?P<transductor_id>[0-9]+)/$', views.report, name="report"),
    url(r'^open_pdf/(?P<transductor_id>[0-9]+)/$', views.open_pdf, name="open_pdf"),
    url(r'^invoice/(?P<transductor_id>[0-9]+)/$', views.invoice, name="invoice"),
    url(r'^transductors_filter/$', views.transductors_filter, name="transductors_filter"),
    url(r'^transductor_list/$', views.transductor_list, name="transductor_list"),
    url(r'^get_data_by_transductor/(?P<transductor_id>[0-9]+)/$', views.get_measurements_filter_transductor, name="get_measurements_filter_transductor"),
    url(r'^list_transductors/$', views.list_transductors, name="list_transductors"),
    url(r'^return_chart/$', views.return_chart, name="return_chart"),
]

src/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^dashboard/$', views.dashboard, name="dashboard"),
    url(r'^$', views.show_login, name="home"),
    url(r'^login/$', views.show_login, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^register/', views.register, name="register"),
    url(r'^list_user_edit/', views.list_user_edit, name="list_user_edit"),
    url(r'^list_user_delete/',
        views.list_user_delete,
        name="list_user_delete"),
    url(r'^edit_user/(?P<user_id>[0-9]+)/',
        views.edit_user,
        name="edit_user"),
    url(r'^delete_user/(?P<user_id>[0-9]+)/',
        views.delete_user,
        name="delete_user"),
    url(r'^self_edit/', views.self_edit_user, name="self_edit_user"),
    url(r'^logging_list/', views.logging_list, name="logging_list"),
    url(r'^change_password/', views.change_password, name="change_password"),
]

src/report/models.py
from __future__ import unicode_literals

from django.db import models


class Report(models.Model):

    class Meta:
        permissions = (
            ("can_generate", "Can Generate Reports"),
        )
    """Function to fix single permission exception"""

    def _get_all_permissions(opts, ctype):
        builtin = _get_builtin_permissions(opts)
        custom = list(opts.permissions)
        _check_permission_clashing(custom, builtin, ctype)
        return builtin + custom

src/report/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from django.core.urlresolvers import reverse_lazy, reverse
from django.core import serializers
from cStringIO import StringIO
from reportlab.platypus.flowables import Image
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

from django.http import HttpResponse
from django.utils.translation import ugettext as _

import datetime

from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from matplotlib.dates import DateFormatter
import matplotlib.patches as mpatches

from transductor.models import EnergyMeasurements, EnergyTransductor
from transductor.models import TransductorModel
import json


def create_graphic(path, array_date, array_dateb,
                   array_datec, array_data, label):
    title = _('Monitoring') + ' ' + label

    fig = Figure()

    ax = fig.add_subplot(111)
    bx = fig.add_subplot(111)
    cx = fig.add_subplot(111)
    x = []
    y = []
    yb = []
    yc = []
    xb = []
    xc = []

    for i in range(len(array_data)):
        x.append(array_data[i])
        y.append(array_date[i])
        xb.append(array_data[i])
        xc.append(array_data[i])
        yb.append(array_dateb[i])
        yc.append(array_datec[i])

    ax.plot_date(x, y, '-')
    bx.plot_date(xb, yb, '-')
    cx.plot_date(xc, yc, '-')

    patch1 = mpatches.Patch(color='blue', label=_('Phase 1'))
    patch2 = mpatches.Patch(color='green', label=_('Phase 2'))
    patch3 = mpatches.Patch(color='red', label=_('Phase 3'))

    z = [patch1, patch2, patch3]

    cx.legend(handles=z, loc=1)

    ax.set_title(title)
    ax.set_xlabel(_('Date'))
    ax.set_ylabel(label)
    ax.xaxis.set_major_formatter(DateFormatter('%Y-%m-%d'))
    fig.autofmt_xdate()
    canvas = FigureCanvas(fig)

    fig.savefig(path)

    return path


def generatePdf(transductor_id):
    import time
    from reportlab.lib.enums import TA_JUSTIFY
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch

    doc = SimpleDocTemplate("src/report/static/Relatorio"+transductor_id+".pdf",
                            pagesize=letter,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=18)
    Story = []
    logo = "src/report/static/currentGraphic"+transductor_id+".png"
    logo2 = "src/report/static/voltageGraphic"+transductor_id+".png"
    logo3 = "src/report/static/activePowerGraphic"+transductor_id+".png"
    logo4 = "src/report/static/reactivePowerGraphic"+transductor_id+".png"
    logo5 = "src/report/static/apparentPowerGraphic"+transductor_id+".png"

    magName = "Pythonista"
    issueNum = 12
    subPrice = "99.00"
    limitedDate = "03/05/2010"
    freeGift = "tin foil hat"

    formatted_time = time.ctime()
    full_name = "SME-UnB"
    address_parts = ["Campus Universitario UnB", "Brasilia-DF, 70910-900"]

    im = Image(logo, 8 * inch, 5 * inch)
    im2 = Image(logo2, 8 * inch, 5 * inch)
    im3 = Image(logo3, 8 * inch, 5 * inch)
    im4 = Image(logo4, 8 * inch, 5 * inch)
    im5 = Image(logo5, 8 * inch, 5 * inch)

    Story.append(im)
    Story.append(im2)
    Story.append(im3)
    Story.append(im4)
    Story.append(im5)

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Justify', alignment=TA_JUSTIFY))
    ptext = '<font size=12>%s</font>' % formatted_time

    Story.append(Paragraph(ptext, styles["Normal"]))
    Story.append(Spacer(1, 12))

    ptext = '<font size=12>%s</font>' % full_name
    Story.append(Paragraph(ptext, styles["Normal"]))
    for part in address_parts:
        ptext = '<font size=12>%s</font>' % part.strip()
        Story.append(Paragraph(ptext, styles["Normal"]))

    Story.append(Spacer(1, 12))
    Story.append(Spacer(1, 12))
    ptext = '<font size=12>{ % trans Report Energy Monitoring % }</font>'
    Story.append(Paragraph(ptext, styles["Normal"]))

    doc.build(Story)
    return 1


def __minValue(arrayData):

    arrayData.sort()
    return arrayData[0]


def __maxValue(arrayData):

    arrayData.sort(reverse=True)

    return arrayData[0]


def __average(arrayData):
    total = 0
    for i in arrayData:
        total += i

    if(len(arrayData) != 0):
        return total / len(arrayData)
    else:
        return 0

@login_required
def report(request, transductor_id):
    now = datetime.datetime.now()
    delta = datetime.timedelta(days=1)

    date = []
    data = []

    voltage_a = []
    voltage_b = []
    voltage_c = []
    current_a = []
    current_b = []
    current_c = []
    active_power_a = []
    active_power_b = []
    active_power_c = []
    reactive_power_a = []
    reactive_power_b = []
    reactive_power_c = []
    apparent_power_a = []
    apparent_power_b = []
    apparent_power_c = []

    for i in EnergyMeasurements.objects.all().filter(transductor=EnergyTransductor.objects.get(id=transductor_id)):

        date.append(i.collection_date)
        voltage_a.append(i.voltage_a)
        voltage_b.append(i.voltage_b)
        voltage_c.append(i.voltage_c)
        current_a.append(i.current_a)
        current_b.append(i.current_b)
        current_c.append(i.current_c)
        active_power_a.append(i.active_power_a)
        active_power_b.append(i.active_power_b)
        active_power_c.append(i.active_power_c)
        reactive_power_a.append(i.reactive_power_a)
        reactive_power_b.append(i.reactive_power_b)
        reactive_power_c.append(i.reactive_power_c)
        apparent_power_a.append(i.apparent_power_a)
        apparent_power_b.append(i.apparent_power_b)
        apparent_power_c.append(i.apparent_power_c)


    create_graphic(
        'src/report/static/currentGraphic' + transductor_id + '.png',
        current_a,
        current_b,
        current_c,
        date,
        _('Current'))

    create_graphic(
        'src/report/static/voltageGraphic' + transductor_id + '.png',
        voltage_a,
        voltage_b,
        voltage_c,
        date,
        _('Voltage'))

    create_graphic(
        'src/report/static/activePowerGraphic' + transductor_id + '.png',
        active_power_a,
        active_power_b,
        active_power_c,
        date,
        _('Active Power'))

    create_graphic(
        'src/report/static/reactivePowerGraphic' + transductor_id + '.png',
        reactive_power_a,
        reactive_power_b,
        reactive_power_c,
        date,
        _('Reactive Power'))

    create_graphic(
        'src/report/static/apparentPowerGraphic' + transductor_id + '.png',
        apparent_power_a,
        apparent_power_b,
        apparent_power_c,
        date,
        _('Apparent Power'))

    generatePdf(transductor_id)

    maxVoltage = [__maxValue(voltage_a),
                  __maxValue(voltage_b),
                  __maxValue(voltage_c)]

    minVoltage = [__minValue(voltage_a),
                  __minValue(voltage_b),
                  __minValue(voltage_c)]

    averageVoltage = [__average(voltage_a),
                      __average(voltage_b),
                      __average(voltage_c)]

    maxCurrent = [__maxValue(current_a),
                  __maxValue(current_b),
                  __maxValue(current_c)]

    minCurrent = [__minValue(current_a),
                  __minValue(current_b),
                  __minValue(current_c)]

    averageCurrent = [__average(current_a),
                      __average(current_b),
                      __average(current_c)]

    maxActivePower = [__maxValue(active_power_a),
                      __maxValue(active_power_b),
                      __maxValue(active_power_c)]

    minActivePower = [__minValue(active_power_a),
                      __minValue(active_power_b),
                      __minValue(active_power_c)]

    averageActivePower = [__average(active_power_a),
                          __average(active_power_b),
                          __average(active_power_c)]

    maxReactivePower = [__maxValue(reactive_power_a),
                        __maxValue(reactive_power_b),
                        __maxValue(reactive_power_c)]

    minReactivePower = [__minValue(reactive_power_a),
                        __minValue(reactive_power_b),
                        __minValue(reactive_power_c)]

    averageReactivePower = [__average(reactive_power_a),
                            __average(reactive_power_b),
                            __average(reactive_power_c)]

    maxApparentPower = [__maxValue(apparent_power_a),
                        __maxValue(apparent_power_b),
                        __maxValue(apparent_power_c)]

    minApparentPower = [__minValue(apparent_power_a),
                        __minValue(apparent_power_b),
                        __minValue(apparent_power_c)]

    averageApparentPower = [__average(apparent_power_a),
                            __average(apparent_power_b),
                            __average(apparent_power_c)]

    VoltageInformation = {'max': maxVoltage, 'min': minVoltage,
                          'average': averageVoltage}

    currentInformation = {'max': maxCurrent, 'min': minCurrent,
                          'average': averageCurrent}

    activePowerInformation = {'max': maxActivePower, 'min': minActivePower,
                              'average': averageActivePower}

    reactivePowerInformation = {'max': maxReactivePower,
                                'min': minReactivePower,
                                'average': averageReactivePower}

    apparentPowerInformation = {'max': maxApparentPower,
                                'min': minApparentPower,
                                'average': averageApparentPower}

    information = {'voltage': VoltageInformation,
                   'Current': currentInformation,

src/report/templates/invoice/invoice.html
<!DOCTYPE html>
{% extends "users/dashboard.html" %}
{% load i18n %}

{% block title %}
<title>{% trans "Simulated invoice" %}</title>
{% endblock %}

{% block dashboard_content %}
<head>
  <meta charset="UTF-8">
  <script>
  //Calculo do consumo de Watts
  function CalcWatts() {
      var current = document.getElementById("current_input").value;
      var amperage = document.getElementById("amperage_input").value;
      var value = document.getElementById("kw").innerHTML = '<br>' + 'Valor: '+ ((current * amperage)/1000) + ' KiloWatts';
      var kw = document.getElementById("kw_input").value = ((current * amperage)/1000);

  }
  //Calculo do consumo de KWh
  function CalcKw() {
      var kw = document.getElementById("kw_input").value;
      var hours = document.getElementById("hours_input").value;
      var price = document.getElementById("kwh").innerHTML = '<br>' + 'Valor utilizado: ' + (kw * hours) + ' KW/h';
      var kwh = document.getElementById("kwh_input").value = (kw * hours);

  }
  //Calculo do valor do consumo mensal
  function CalcValuePrice() {
      var kwh = document.getElementById("kwh_input").value;
      var kwh_price = document.getElementById("khw_price").value;
      var radios = document.getElementsByName('band');
      var soma = 0;
      for (var i = 0, length = radios.length; i < length; i++) {
        if (radios[i].checked) {
          if (radios[i].value === "red") {
            var arredondadoParaBaixo = Math.floor(kwh/100);
            soma = arredondadoParaBaixo* 5.5;
          }
          if (radios[i].value === "yellow")  {
            var arredondadoParaBaixo = Math.floor(kwh/100);
            soma = arredondadoParaBaixo*2.5;
          }
          break;
        }
      }
      var price = document.getElementById("price").innerHTML = '<br>' + 'Valor: R$'+ ((kwh * kwh_price)+soma);

  }
  </script>
</head>
<body>
  <center>
    <div class="form-group">
      <h1 class='text-center'>{% trans "Simulate invoice" %}</h1>
      <div class="row">
        <div class="col-md-2 col-md-offset-5">
          <a class="btn btn-primary btn-lg btn-block" href="{% url 'report:open_pdf' transductor_id %}" target="_blank" role="button">{% trans "Generate pdf" %}&raquo;</a>
        </div>
      </div>
    </div>
    <br>
    {% trans "Operations to be used to simulate invoice:" %}

    <ul id="list">
      <li>{% trans "Watts Calculation" %}</li>
      <li>{% trans "Calculation of Kw / h" %}</li>
      <li>{% trans "Monthly consumption" %}</li>
    </ul>

    <h1>{% trans "KiloWatts value" %} :</h1>
    <br>
    <label>{% trans "Power in kiloWatts through amperage and current ratio" %}: </label>
    <br>
    <label>{% trans "Enter the approximate value of the current" %}: </label>
    <input type="text" id="current_input" tabindex="5" size="5"/>
    <br>
    <label for="amperage">{% trans "Enter the approximate amperage value" %}: </label>
    <input type="text" id="amperage_input" tabindex="5" size="5"/>
    <label id="kw"></label>
    <br>
    <button type="button" onclick="CalcWatts()">{% trans "Calculate" %}</button>


    <h1>{% trans "KW / h consumption" %}:</h1>
    <br>
    <label>{% trans "Quantity power measured in KiloWatts for one hour" %}: </label>
    <br>
    <label>{% trans "Enter the power of KW" %}: </label>
    <input type="text" id="kw_input" tabindex="5" size="5"/>
    <br>
    <label>{% trans "Enter the number of hours" %}: </label>
    <input type="text" id="hours_input" tabindex="5" size="5"/>
    <label id="kwh"></label>
    <br>
    <button type="button" onclick="CalcKw()">{% trans "Calculate" %}</button>

    <h1>{% trans "Value of consumption" %}: </h1>

    <br>
    <form>
      <label>{% trans "Flag" %}: </label>
    <br>
      <input type="radio" name="band" value="red" checked> {% trans "Red" %}<br>
      <input type="radio" name="band" value="yellow"> {% trans "Yellow" %}<br>
      <input type="radio" name="band" value="green">{% trans "Green" %}
    </form>
    <br>
    <label>{% trans "Total consumption" %}: </label>
    <br>
    <label>{% trans "Enter the amount of KW / h used:" %} </label>
    <input type="text" id="kwh_input" tabindex="5" size="5"/>
    <br>
    <label>{% trans "Digite o preço do KW/h" %}: </label>
    <input type="text" id="khw_price" tabindex="5" size="8"/ value="0.5041085">
    <label id="price"></label>
    <br>
    <button type="button" onclick="CalcValuePrice()">{% trans "Calculate" %}</button>
    </center>
  </body>
</html>
{% endblock %}

src/report/templates/invoice/transductor_list.html
{% extends "users/dashboard.html" %}
{% load i18n %}
{% block dashboard_content %}

<div class="margin">
  <h1 class="text-center">{% trans "List of Transductors:" %}</h>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="margin">
        <table class ="table table-bordered">
          <tr>
            <th>{% trans "Serial Number" %}</th>
            <th>{% trans "IP Address" %}</th>
            <th>{% trans "Description" %}</th>
            <th>{% trans "Creation Date" %}</th>
            <th> </th>
          </tr>
          {% for transductor in transductors %}
          <tr>
            <td>{{transductor.serie_number}}</td>
            <td>{{transductor.ip_address}}</td>
            <td>{{transductor.description}}</td>
            <td>{{transductor.creation_date}}</td>
            <td><a href="{% url 'report:invoice' transductor.id %}"><button class ="btn btn-success" type="button" name="button"><span class="glyphicon glyphicon-stats" aria-hidden="true"></span></button></a></td>
          </tr>
          {% endfor %}
        </table>
      </div>

    </div>
  </div>
{% endblock %}