src/SME_UnB/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^transductor/', include('transductor.urls',
                                  namespace="transductor")),
    url(r'^accounts/', include('users.urls', namespace="users")),
    url(r'^reports/', include('report.urls', namespace="report")),
    url(r'^retrieve_password/', include('retrieve_password.urls', namespace="retrieve")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

src/alerts/urls.py
from django.conf.urls import url

from . import views

app_name = 'alerts'
urlpatterns = [
    url(r'^alerts/', views, name="alert"),
]

src/report/urls.py
from django.conf.urls import url

from . import views

app_name = 'report'
urlpatterns = [
    url(r'^report/(?P<transductor_id>[0-9]+)/$', views.report, name="report"),
    url(r'^open_pdf/(?P<transductor_id>[0-9]+)/$', views.open_pdf, name="open_pdf"),
    url(r'^invoice/(?P<transductor_id>[0-9]+)/$', views.invoice, name="invoice"),
    url(r'^transductors_filter/$', views.transductors_filter, name="transductors_filter"),
    url(r'^transductor_list/$', views.transductor_list, name="transductor_list"),
    url(r'^get_data_by_transductor/(?P<transductor_id>[0-9]+)/$', views.get_measurements_filter_transductor, name="get_measurements_filter_transductor"),
    url(r'^list_transductors/$', views.list_transductors, name="list_transductors"),
    url(r'^return_chart/$', views.return_chart, name="return_chart"),
]

src/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^dashboard/$', views.dashboard, name="dashboard"),
    url(r'^$', views.show_login, name="home"),
    url(r'^login/$', views.show_login, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^register/', views.register, name="register"),
    url(r'^list_user_edit/', views.list_user_edit, name="list_user_edit"),
    url(r'^list_user_delete/',
        views.list_user_delete,
        name="list_user_delete"),
    url(r'^edit_user/(?P<user_id>[0-9]+)/',
        views.edit_user,
        name="edit_user"),
    url(r'^delete_user/(?P<user_id>[0-9]+)/',
        views.delete_user,
        name="delete_user"),
    url(r'^self_edit/', views.self_edit_user, name="self_edit_user"),
    url(r'^logging_list/', views.logging_list, name="logging_list"),
    url(r'^change_password/', views.change_password, name="change_password"),
]

src/report/models.py
from __future__ import unicode_literals

from django.db import models


class Report(models.Model):

    class Meta:
        permissions = (
            ("can_generate", "Can Generate Reports"),
        )
    """Function to fix single permission exception"""

    def _get_all_permissions(opts, ctype):
        builtin = _get_builtin_permissions(opts)
        custom = list(opts.permissions)
        _check_permission_clashing(custom, builtin, ctype)
        return builtin + custom

src/retrieve_password/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

src/transductor/forms.py
from django import forms
from .models import EnergyTransductor, TransductorModel


class EnergyForm(forms.ModelForm):
    transductor_model = forms.ModelChoiceField(queryset=TransductorModel.objects.all(), required=True, initial=0)

    class Meta:
        model = EnergyTransductor
        fields = ('serie_number', 'ip_address', 'description',)

class DeleteEnergyForm(forms.ModelForm):
    class Meta:
        model = EnergyTransductor
        fields = []

src/SME_UnB/views.py
from django.shortcuts import render


def index(request):
    template_name = 'index.html'

    return render(request, template_name)

src/alerts/views.py
# from django.shortcuts import render

# from transductor.models import EnergyTransductor

# Create your views here.


# def index(request):
#   return render(request, "alerts/index.html")

src/data_reader/views.py
# from django.shortcuts import render

src/report/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from django.core.urlresolvers import reverse_lazy, reverse
from django.core import serializers
from cStringIO import StringIO
from reportlab.platypus.flowables import Image
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

from django.http import HttpResponse
from django.utils.translation import ugettext as _

import datetime

from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from matplotlib.dates import DateFormatter
import matplotlib.patches as mpatches

from transductor.models import EnergyMeasurements, EnergyTransductor
from transductor.models import TransductorModel
import json


def create_graphic(path, array_date, array_dateb,
                   array_datec, array_data, label):
    title = _('Monitoring') + ' ' + label

    fig = Figure()

    ax = fig.add_subplot(111)
    bx = fig.add_subplot(111)
    cx = fig.add_subplot(111)
    x = []
    y = []
    yb = []
    yc = []
    xb = []
    xc = []

    for i in range(len(array_data)):
        x.append(array_data[i])
        y.append(array_date[i])
        xb.append(array_data[i])
        xc.append(array_data[i])
        yb.append(array_dateb[i])
        yc.append(array_datec[i])

    ax.plot_date(x, y, '-')
    bx.plot_date(xb, yb, '-')
    cx.plot_date(xc, yc, '-')

    patch1 = mpatches.Patch(color='blue', label=_('Phase 1'))
    patch2 = mpatches.Patch(color='green', label=_('Phase 2'))
    patch3 = mpatches.Patch(color='red', label=_('Phase 3'))

    z = [patch1, patch2, patch3]

    cx.legend(handles=z, loc=1)

    ax.set_title(title)
    ax.set_xlabel(_('Date'))
    ax.set_ylabel(label)
    ax.xaxis.set_major_formatter(DateFormatter('%Y-%m-%d'))
    fig.autofmt_xdate()
    canvas = FigureCanvas(fig)

    fig.savefig(path)

    return path


def generatePdf(transductor_id):
    import time
    from reportlab.lib.enums import TA_JUSTIFY
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch

    doc = SimpleDocTemplate("src/report/static/Relatorio"+transductor_id+".pdf",
                            pagesize=letter,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=18)
    Story = []
    logo = "src/report/static/currentGraphic"+transductor_id+".png"
    logo2 = "src/report/static/voltageGraphic"+transductor_id+".png"
    logo3 = "src/report/static/activePowerGraphic"+transductor_id+".png"
    logo4 = "src/report/static/reactivePowerGraphic"+transductor_id+".png"
    logo5 = "src/report/static/apparentPowerGraphic"+transductor_id+".png"

    magName = "Pythonista"
    issueNum = 12
    subPrice = "99.00"
    limitedDate = "03/05/2010"
    freeGift = "tin foil hat"

    formatted_time = time.ctime()
    full_name = "SME-UnB"
    address_parts = ["Campus Universitario UnB", "Brasilia-DF, 70910-900"]

    im = Image(logo, 8 * inch, 5 * inch)
    im2 = Image(logo2, 8 * inch, 5 * inch)
    im3 = Image(logo3, 8 * inch, 5 * inch)
    im4 = Image(logo4, 8 * inch, 5 * inch)
    im5 = Image(logo5, 8 * inch, 5 * inch)

    Story.append(im)
    Story.append(im2)
    Story.append(im3)
    Story.append(im4)
    Story.append(im5)

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Justify', alignment=TA_JUSTIFY))
    ptext = '<font size=12>%s</font>' % formatted_time

    Story.append(Paragraph(ptext, styles["Normal"]))
    Story.append(Spacer(1, 12))

    ptext = '<font size=12>%s</font>' % full_name
    Story.append(Paragraph(ptext, styles["Normal"]))
    for part in address_parts:
        ptext = '<font size=12>%s</font>' % part.strip()
        Story.append(Paragraph(ptext, styles["Normal"]))

    Story.append(Spacer(1, 12))
    Story.append(Spacer(1, 12))
    ptext = '<font size=12>{ % trans Report Energy Monitoring % }</font>'
    Story.append(Paragraph(ptext, styles["Normal"]))

    doc.build(Story)
    return 1


def __minValue(arrayData):

    arrayData.sort()
    return arrayData[0]


def __maxValue(arrayData):

    arrayData.sort(reverse=True)

    return arrayData[0]


def __average(arrayData):
    total = 0
    for i in arrayData:
        total += i

    if(len(arrayData) != 0):
        return total / len(arrayData)
    else:
        return 0

@login_required
def report(request, transductor_id):
    now = datetime.datetime.now()
    delta = datetime.timedelta(days=1)

    date = []
    data = []

    voltage_a = []
    voltage_b = []
    voltage_c = []
    current_a = []
    current_b = []
    current_c = []
    active_power_a = []
    active_power_b = []
    active_power_c = []
    reactive_power_a = []
    reactive_power_b = []
    reactive_power_c = []
    apparent_power_a = []
    apparent_power_b = []
    apparent_power_c = []

    for i in EnergyMeasurements.objects.all().filter(transductor=EnergyTransductor.objects.get(id=transductor_id)):

        date.append(i.collection_date)
        voltage_a.append(i.voltage_a)
        voltage_b.append(i.voltage_b)
        voltage_c.append(i.voltage_c)
        current_a.append(i.current_a)
        current_b.append(i.current_b)
        current_c.append(i.current_c)
        active_power_a.append(i.active_power_a)
        active_power_b.append(i.active_power_b)
        active_power_c.append(i.active_power_c)
        reactive_power_a.append(i.reactive_power_a)
        reactive_power_b.append(i.reactive_power_b)
        reactive_power_c.append(i.reactive_power_c)
        apparent_power_a.append(i.apparent_power_a)
        apparent_power_b.append(i.apparent_power_b)
        apparent_power_c.append(i.apparent_power_c)


    create_graphic(
        'src/report/static/currentGraphic' + transductor_id + '.png',
        current_a,
        current_b,
        current_c,
        date,
        _('Current'))

    create_graphic(
        'src/report/static/voltageGraphic' + transductor_id + '.png',
        voltage_a,
        voltage_b,
        voltage_c,
        date,
        _('Voltage'))

    create_graphic(
        'src/report/static/activePowerGraphic' + transductor_id + '.png',
        active_power_a,
        active_power_b,
        active_power_c,
        date,
        _('Active Power'))

    create_graphic(
        'src/report/static/reactivePowerGraphic' + transductor_id + '.png',
        reactive_power_a,
        reactive_power_b,
        reactive_power_c,
        date,
        _('Reactive Power'))

    create_graphic(
        'src/report/static/apparentPowerGraphic' + transductor_id + '.png',
        apparent_power_a,
        apparent_power_b,
        apparent_power_c,
        date,
        _('Apparent Power'))

    generatePdf(transductor_id)

    maxVoltage = [__maxValue(voltage_a),
                  __maxValue(voltage_b),
                  __maxValue(voltage_c)]

    minVoltage = [__minValue(voltage_a),
                  __minValue(voltage_b),
                  __minValue(voltage_c)]

    averageVoltage = [__average(voltage_a),
                      __average(voltage_b),
                      __average(voltage_c)]

    maxCurrent = [__maxValue(current_a),
                  __maxValue(current_b),
                  __maxValue(current_c)]

    minCurrent = [__minValue(current_a),
                  __minValue(current_b),
                  __minValue(current_c)]

    averageCurrent = [__average(current_a),
                      __average(current_b),
                      __average(current_c)]

    maxActivePower = [__maxValue(active_power_a),
                      __maxValue(active_power_b),
                      __maxValue(active_power_c)]

    minActivePower = [__minValue(active_power_a),
                      __minValue(active_power_b),
                      __minValue(active_power_c)]

    averageActivePower = [__average(active_power_a),
                          __average(active_power_b),
                          __average(active_power_c)]

    maxReactivePower = [__maxValue(reactive_power_a),
                        __maxValue(reactive_power_b),
                        __maxValue(reactive_power_c)]

    minReactivePower = [__minValue(reactive_power_a),
                        __minValue(reactive_power_b),
                        __minValue(reactive_power_c)]

    averageReactivePower = [__average(reactive_power_a),
                            __average(reactive_power_b),
                            __average(reactive_power_c)]

    maxApparentPower = [__maxValue(apparent_power_a),
                        __maxValue(apparent_power_b),
                        __maxValue(apparent_power_c)]

    minApparentPower = [__minValue(apparent_power_a),
                        __minValue(apparent_power_b),
                        __minValue(apparent_power_c)]

    averageApparentPower = [__average(apparent_power_a),
                            __average(apparent_power_b),
                            __average(apparent_power_c)]

    VoltageInformation = {'max': maxVoltage, 'min': minVoltage,
                          'average': averageVoltage}

    currentInformation = {'max': maxCurrent, 'min': minCurrent,
                          'average': averageCurrent}

    activePowerInformation = {'max': maxActivePower, 'min': minActivePower,
                              'average': averageActivePower}

    reactivePowerInformation = {'max': maxReactivePower,
                                'min': minReactivePower,
                                'average': averageReactivePower}

    apparentPowerInformation = {'max': maxApparentPower,
                                'min': minApparentPower,
                                'average': averageApparentPower}

    information = {'voltage': VoltageInformation,
                   'Current': currentInformation,

src/transductor/views.py
from .models import EnergyTransductor, TransductorModel
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from .forms import EnergyForm, DeleteEnergyForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required


def index(request):
    template_name = 'transductor/index.html'
    transductors_list = EnergyTransductor.objects.all()

    return render(request, template_name,
                  {'transductors_list': transductors_list})


@login_required
def detail(request, transductor_id):
    template_name = 'transductor/detail.html'
    transductor = get_object_or_404(EnergyTransductor, pk=transductor_id)

    measurements = EnergyTransductor.objects \
        .get(id=transductor_id).energymeasurements_set.all()
    paginator = Paginator(measurements, 4)
    page = request.GET.get('page')

    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    return render(request, template_name,
                  {'measurements': data, 'transductor': transductor})


@login_required
def new(request):
    if request.POST:
        form = EnergyForm(request.POST)

        if form.is_valid():
            transductor = EnergyTransductor()
            transductor.serie_number = form.cleaned_data['serie_number']
            transductor.ip_address = form.cleaned_data['ip_address']
            transductor.description = form.cleaned_data['description']
            transductor.model = form.cleaned_data['transductor_model']
            transductor.creation_date = timezone.now()

            try:
                transductor.save()
            except ValidationError, err:
                errors = '; '.join(err.messages)
                return render(request, 'transductor/new.html', {'form': form, 'errors': errors})

            return redirect('transductor:detail', transductor_id=transductor.id)
    else:
        form = EnergyForm()

    return render(request, 'transductor/new.html', {'form': form})



@login_required
def edit(request, transductor_id):
    transductor = get_object_or_404(EnergyTransductor, pk=transductor_id)

    if request.POST:
        form = EnergyForm(request.POST, instance=transductor, initial={'model': transductor.model})
        if form.has_changed() and form.is_valid():
            for data in form.changed_data:
                setattr(form.instance, data, form.cleaned_data[data])

        if form.is_valid():
            form.save()
            return redirect('transductor:index')
        else:
            # Add no changes error
            pass
    else:
        form = EnergyForm(instance=transductor, initial={'model': transductor.model})

    return render(request, 'transductor/new.html', {'form': form})


@login_required
def delete(request, transductor_id):
    transductor = get_object_or_404(EnergyTransductor, pk=transductor_id)

    if request.POST:
        form = DeleteEnergyForm(request.POST, instance=transductor)

        if form.is_valid():
            transductor.delete()

    return HttpResponseRedirect(reverse('transductor:index'))


def model_index(request):
    template_name = 'transductor/model_index.html'
    transductors_models = TransductorModel.objects.all()

    return render(request, template_name,
                  {'transductors_models': transductors_models})

src/templates/base.html
{% load bootstrap3 %} {% bootstrap_css %} {% bootstrap_messages %} {% load i18n %} {% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'data_reader/css/style.css' %}" />

<head>
    {% block title %}
    <title>SME - UnB</title>
    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/simple-sidebar.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'data_reader/css/style.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'users/css/style.css' %}" media="screen,projection" />
    <script src="https://js.pusher.com/3.2/pusher.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript" src="{% static 'users/js/pusher.js' %}"></script>
    <script type="text/javascript" src="{% static 'users/js/sidebar.js' %}"></script>
</head>

<body>
    {% include "notification.html" %}
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="margin-bottom: 0px;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">{% trans "Toggle navigation " %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button> {% if user.is_authenticated %}
                <a class="navbar-brand" href="{% url 'users:dashboard'%}">SME - UnB</a> {% else %}
                <a class="navbar-brand" href="/">SME - UnB</a> {% endif %}
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li><a href="#about">{% trans "About" %}</a></li>
                    <li><a href="#contact">{% trans "Contact" %}</a></li>
                </ul>
                <div class="navbar-right" style="margin-right:30px">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="">{% include "languages.html" %}</li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'users:dashboard'%}"><b>{{ request.user.username }}</b></a></li>
                    </ul>
                    <a onclick="return confirm('Voce tem certeza ?')" href="{% url 'users:logout'%}"><button type = "button" class = "btn btn-danger navbar-btn">
                      <span class= "glyphicon glyphicon-log-out" aria-hidden="true"> </span> {% trans "Logout" %}
                      </button></a>
                </div>
                {% else %}
                <ul class="nav navbar-nav">
                    <li><a href="#about">{% trans "About" %}</a></li>
                    <li><a href="#contact">{% trans "Contact" %}</a></li>
                </ul>
                <div class=" navbar-right" style="margin-right:30px">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="">{% include "languages.html" %}</li>
                    </ul>
                    <a href="{% url 'users:login'%}">
                        <button type="button" class="btn btn-default navbar-btn">
                        <span class= "glyphicon glyphicon-log-in" aria-hidden="true"> </span> {% trans "Login" %}
                      </button>
                    </a>
                </div>
                {% endif %}
            </div>
    </nav>
    <div class="container-fluid" style="padding-top: 50px;">
        {% block body %} {% endblock %}
    </div>
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>

src/templates/index.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
    <title>SME - UnB</title>
{% endblock %}

{% block body %}
<div class="jumbotron">
  <div class="container">
      <h1>{% trans "Welcome!" %}</h1>
    <p>{% trans "SME - UnB is a web platform to monitor measurements from energy transductors." %}</p>
      <p><a class="btn btn-primary btn-lg" href="https://gitlab.com/brenddongontijo/SME-UnB" role="button">{% trans "Learn more"%} &raquo;</a></p>
  </div>
</div>
{% endblock %}

src/templates/languages.html
{% load i18n %}

{% get_available_languages as LANGUAGES %}

<div class="idiomas" style = "    margin-top: 8px; margin-left: 8px;">
  <form action="/i18n/setlang/" method="post">{% csrf_token %}
    <select class = "form-control" name="language" onchange="submit()">
      <option> {% trans "Change Language" %}</option>
        {% for lang in LANGUAGES %}
      <option value="{{ lang.0 }}">{{ lang.1 }}</option>
      {% endfor %}
    </select>
  </form>
</div>

src/templates/notification.html
<div class="custom-alert" id="allert-container">

</div>