src/SME_UnB/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^transductor/', include('transductor.urls',
                                  namespace="transductor")),
    url(r'^accounts/', include('users.urls', namespace="users")),
    url(r'^reports/', include('report.urls', namespace="report")),
    url(r'^retrieve_password/', include('retrieve_password.urls', namespace="retrieve")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

src/report/urls.py
from django.conf.urls import url

from . import views

app_name = 'report'
urlpatterns = [
    url(r'^report/(?P<transductor_id>[0-9]+)/$', views.report, name="report"),
    url(r'^open_pdf/(?P<transductor_id>[0-9]+)/$', views.open_pdf, name="open_pdf"),
    url(r'^invoice/(?P<transductor_id>[0-9]+)/$', views.invoice, name="invoice"),
    url(r'^transductors_filter/$', views.transductors_filter, name="transductors_filter"),
    url(r'^transductor_list/$', views.transductor_list, name="transductor_list"),
    url(r'^get_data_by_transductor/(?P<transductor_id>[0-9]+)/$', views.get_measurements_filter_transductor, name="get_measurements_filter_transductor"),
    url(r'^list_transductors/$', views.list_transductors, name="list_transductors"),
    url(r'^return_chart/$', views.return_chart, name="return_chart"),
]

src/retrieve_password/urls.py
from django.conf.urls import url

from . import views

app_name = 'retrieve_password'
urlpatterns = [
url(r'^forgot/', views.forgot_password, name="forgot"),
url(r'^reset/(?P<token>[0-9a-f]+)/', views.confirm_email, name="reset"),
url(r'^reset_password/', views.reset_password, name="reset_password"),
]

src/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^dashboard/$', views.dashboard, name="dashboard"),
    url(r'^$', views.show_login, name="home"),
    url(r'^login/$', views.show_login, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^register/', views.register, name="register"),
    url(r'^list_user_edit/', views.list_user_edit, name="list_user_edit"),
    url(r'^list_user_delete/',
        views.list_user_delete,
        name="list_user_delete"),
    url(r'^edit_user/(?P<user_id>[0-9]+)/',
        views.edit_user,
        name="edit_user"),
    url(r'^delete_user/(?P<user_id>[0-9]+)/',
        views.delete_user,
        name="delete_user"),
    url(r'^self_edit/', views.self_edit_user, name="self_edit_user"),
    url(r'^logging_list/', views.logging_list, name="logging_list"),
    url(r'^change_password/', views.change_password, name="change_password"),
]

src/users/models.py
"""Directly data manager,logic appliations so as to theirs rules"""
from django.db import models
from django.contrib.auth.base_user import BaseUserManager
import pusher


class EmailUserManager(BaseUserManager):
    pass


class UserPermissions(models.Model):

    class Meta:
        permissions = (
            ("can_delete_user", "Can delete Users"),
            ("can_edit_user", "Can edit Users"),
        )


class UserNotification(object):

    @staticmethod
    def send_notification(id, message):
        APP_ID = '259103'
        APP_KEY = '01346f7690ac693e7adb'
        APP_SECRET = '20bf35aeec654118b90c'
        NOTIFICATION_PREFIX = 'notification_'
        CREATE_EVENT = 'create'
        print(NOTIFICATION_PREFIX + str(id))
        pusher_client = pusher.Pusher(app_id=APP_ID,
                                      key=APP_KEY,
                                      secret=APP_SECRET,
                                      ssl=True)

        pusher_client.trigger(NOTIFICATION_PREFIX + str(id),
                              CREATE_EVENT, message)

src/users/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Permission
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages
from django.db import IntegrityError
from django.contrib.auth.decorators import user_passes_test

from django.http import HttpResponse
from django.core.mail import send_mail
from django.core import mail
from SME_UnB.settings import EMAIL_HOST_USER
from django.contrib.auth import update_session_auth_hash

import os

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import json
import logging
import hashlib
import datetime


def home(request):
    return render(request, 'users/home.html')


@login_required
def dashboard(request):
    return render(request, 'users/dashboard.html')


def show_login(request):
    if request.method == "GET":
        return render(request, "users/login.html")
    else:
        context = make_login(request)

        if context.get('is_logged'):
            return HttpResponseRedirect(reverse("users:dashboard"))
        else:
            return render(request, "users/login.html", context)


def make_login(request):
    form = request.POST
    username = form.get('username')
    password = form.get('password')

    user = authenticate(username=username, password=password)
    is_logged = False

    if user is not None:
        logger = logging.getLogger(__name__)
        logger.info(user.__str__() + ' User is logged')
        login(request, user)
        message = "Logged"

        is_logged = True
    else:
        message = "Incorrect user"

    context = {
        "is_logged": is_logged,
        "message": message,
    }

    return context


def logout_view(request, *args, **kwargs):
    kwargs['next_page'] = reverse('index')
    logger = logging.getLogger(__name__)
    logger.info(request.user.__str__() + ' Logout ')

    return logout(request, *args, **kwargs)


@login_required
@user_passes_test(lambda user: user.is_staff, login_url='/accounts/dashboard/')
def register(request):

    if request.method == "GET":
        return render(request, 'userRegister/register.html')
    else:
        form = request.POST
        first_name = form.get('first_name')
        last_name = form.get('last_name')
        password = form.get('password')
        confirmPassword = form.get('confirmPassword')
        email = form.get('email')
        user_type = form.get('user_type')

        resultCheck = fullValidationRegister(form)
        resultCheck += fullValidation(form)

        if len(resultCheck) != 0:
            return render(
                request,
                'userRegister/register.html',
                {'falha': resultCheck})

        # Fim do bloco que saira da view
    #    first_name = form.get('first_name')
    #    last_name = form.get('last_name')
    #    password = form.get('password')
    #    email = form.get('email')

        try:
            if user_type == 'common':
                user = User.objects.create_user(first_name=first_name,
                                                last_name=last_name,
                                                password=password,
                                                username=email)
            else:
                user = User.objects.create_superuser(first_name=first_name,
                                                     last_name=last_name,
                                                     password=password,
                                                     username=first_name,
                                                     email=email)

        except IntegrityError as e:
            return render(request, 'userRegister/register.html',
                          {'falha': 'Invalid email, email already exist'})
        except:
            return render(request, 'userRegister/register.html',
                          {'falha': 'unexpected error'})

        give_permission(request, user)
        user.save()
        messages.success(request, 'Usuario registrado com sucesso')


        logger = logging.getLogger(__name__)

        logger.info(request.user.__str__() + ' Registered ' + user.__str__() )

	from django.core import mail
	connection = mail.get_connection()

	# Manually open the connection
	connection.open()

	# Construct an email message that uses the connection
	email1 = mail.EmailMessage(
	    'Hello',
	    'Body goes here',
	    'mds@sof2u.com',
	    [email],
	    connection=connection,
	)
	email1.send() # Send the email
# >>>>>>> forgot_password
# 	"""
#     send_mail(
#             'Account registered with success',
#             'Your account on SME-UNB was successfully created',
#             'mds@sof2u.com',
#             [email],
#             fail_silently=False,
#             )
#     """

    return render(request, 'users/dashboard.html')


def check_name(first_name, last_name):
    if not first_name.isalpha() or not last_name.isalpha():
        return 'Nome deve conter apenas letras'
    else:
        return ''


def check_email(email):
    if '@' not in email or '.' not in email or ' ' in email:
        return ' -- Email inválido! Esse e-mail não esta em um formato válido'
    else:
        return ''


def check_email_exist(email, original_email):
    if User.objects.filter(email=email).exists() and email != original_email:
        return ' -- E-mail já esta cadastrado no nosso banco de dados'
    else:
        return ''


def check_password_lenght(password, confirmPassword):
    if len(password) < 6 and password != confirmPassword:
        return ' -- Senha Inválida, digite uma senha com no mínimo 6 letras'
    else:
        return ''


def check_password(password, confirmPassword):
    if password != confirmPassword:
        return ' -- Senha inválida! Senhas de cadastros diferentes'
    else:
        return ''


def check_current_password(user, currentPassword):

    if not user.check_password(currentPassword):
        return ' -- Campo de Senha atual diferente da Senha Atual!'
    else:
        return ''


def fullValidation(form):
    first_name = form.get('first_name')
    last_name = form.get('last_name')
    email = form.get('email')
    original_email = form.get('original_email')

    resultCheck = ''
    resultCheck += check_name(first_name, last_name)
    resultCheck += check_email(email)
    resultCheck += check_email_exist(email, original_email)

    return resultCheck


def fullValidationRegister(form, user=None):
    currentPassword = form.get('currentPassword')
    password = form.get('password')
    confirmPassword = form.get('confirmPassword')

    resultCheck = ''
    if user is not None:
        resultCheck += check_current_password(user, currentPassword)
        resultCheck += check_password_lenght(password, confirmPassword)
        resultCheck += check_password(password, confirmPassword)

    return resultCheck


@login_required
def list_user_edit(request):

    return __list__(request, 'users/list_user_edit.html')


@login_required
def list_user_delete(request):

    return __list__(request, 'users/list_user_delete.html')


def check_permissions(user):

    has_report_permission = 'checked' if user. \
        has_perm('report.can_generate') else ''
    has_transductor_permission = 'checked' if user. \
        has_perm('transductor.can_view_transductors') else ''
    has_edit_user_permission = 'checked' if user. \
        has_perm('users.can_edit_user') else ''
    has_delete_user_permission = 'checked' if user. \
        has_perm('users.can_delete_user') else ''
    has_see_logging_permission = 'checked' if user. \
        has_perm('users.can_see_logging') else ''

    context = {
        'user': user,
        "can_generate": has_report_permission,
        "view_transductors": has_transductor_permission,
        "edit_users": has_edit_user_permission,
        "delete_users": has_delete_user_permission,
        "see_logging": has_see_logging_permission,
    }

    return context


@login_required
def change_password(request):
    user = User.objects.get(pk=request.user.id)

    if request.method == "GET":
        return render(request, 'users/change_password.html',)

    else:
        form = request.POST
        password = form.get('password')
        currentPassword = form.get('confirmPassword')
        print(currentPassword)

        resultCheck = fullValidationRegister(form, user)
        if len(resultCheck) != 0:
            return __prepare_error_render_self__(request, resultCheck, user)

        user.set_password(password)
        user.save()
        update_session_auth_hash(request, user)
        logger = logging.getLogger(__name__)
        logger.info(request.user.__str__() + ' edited  password')
    return render(request, 'users/dashboard.html')


@login_required
def self_edit_user(request):

    user = User.objects.get(pk=request.user.id)

    if request.method == "GET":
        return render(request, 'users/self_edit.html',)

    else:
        form = request.POST
        first_name = form.get('first_name')
        last_name = form.get('last_name')
        # email = form.get('email')
        email = request.user.username

        resultCheck = fullValidationRegister(form)
        resultCheck += fullValidation(form)

        user.first_name = first_name
        user.last_name = last_name
        user.username = email
        user.email = email
        user.save()

        # login(request,user)
        update_session_auth_hash(request, user)

        logger = logging.getLogger(__name__)
        logger.info(request.user.__str__() + ' edited ' + user.__str__())

        return render(request, 'users/dashboard.html')


@login_required
def edit_user(request, user_id):

src/users/templates/users/change_password.html
{% extends 'users/dashboard.html' %}
{% load i18n %}

{% block title %}
<title>{% trans "Change Password" %}</title>
{% endblock %}

{% block dashboard_content %}
<div class="jumbotron">
  <div class="container">
    <div class="wrapper">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">

          <div class="confirmation">
            <p2>{{info}}</p2>
          </div>

          <h1> </h1>
          <form class="configdiv" action="register" method="post">
            <p2>{{falha}}</p2>
            {% csrf_token %}

            <div class="form-group">
              <p1>{% trans "Current Password :" %}</p1>
              <input type="password" name ="currentPassword" placeholder="current Password" class="form-control">
            </div>
            <div class="form-group">
              <p1>{% trans "New Password:" %}</p1>
              <input type="password" name ="password" placeholder="Password" class="form-control">
            </div>
            <div class="form-group">
                <p1>{% trans "Confirm New Password:" %}</p1>
              <input type="password" name ="confirmPassword" placeholder="confirm password" class="form-control">
            </div>
                <input type="hidden" name="original_email" value="{{user.email}}">
                    <button type="submit" class="btn btn-success" onclick="return confirm('Voce tem certeza que deseja editar sua sena ?')" >{% trans "Edit" %}</button>
            <a class="btn btn-primary" href="{% url 'users:dashboard' %}" role="button">{% trans "Cancel" %}</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block login %}
<form class="navbar-form navbar-right" action="login" method="post">
  <p2 color="red" >{{falha}}</p2>
  {% csrf_token %}
  <div class="form-group">
    <input type="text" name= "Email" placeholder="Email" class="form-control">
  </div>
  <div class="form-group">
    <input type="password" name ="Password" placeholder="Password" class="form-control">
  </div>
  <button type="submit" class="btn btn-success">{% trans "Sign in" %}</button>
</form>
{% endblock %}

src/users/templates/users/dashboard.html
{% extends 'base.html' %}
{% load i18n %}

{% block body %}
<div id="wrapper">
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            {% block breadcrumb %}
            {%if perms.report.can_generate%}
            <li><a href="{% url 'report:transductors_filter' %}">{% trans "Reports" %}<span
                   style="font-size:16px;" class="pull-left hidden-xs showopacity glyphicon
                   glyphicon-dashboard"></span></a></li>
            <li><a href="{% url 'report:return_chart' %}">{% trans "Graphics and Charts"%}<span
                   style="font-size:16px;" class="pull-left hidden-xs showopacity
                   glyphicon glyphicon-stats"></span></a></li>
            {%endif%}
            <li><a href="{% url 'transductor:index'%}">{% trans "Transductors" %}<span
                   style="font-size:16px;" class="pull-left hidden-xs showopacity glyphicon
                   glyphicon-phone"></span></a></li>
            <li><a href="{% url 'report:transductor_list' %}">{% trans "Invoice" %}<span
                   style="font-size:16px;" class="pull-left hidden-xs showopacity glyphicon
                   glyphicon-bullhorn"></span></a></li>
            {% endblock %}
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "User Configurations"%} <span class="caret"></span><span style="font-size:16px;" class="pull-left hidden-xs showopacity glyphicon glyphicon-cog"></span></a>
            <ul class="dropdown-menu forAnimate" role="menu">
                {% if request.user.is_staff %}
                <li><a href="{% url 'users:register' %}">{% trans "Register" %}<span
                       style="font-size:16px;" class="pull-left hidden-xs showopacity glyphicon
                       glyphicon-plus-sign"></span></a></li>
                {% endif %}
                {%if perms.users.can_edit_user%}
                <li><a href="{% url 'users:list_user_edit' %}">{% trans "Edit Users" %}<span
                       style="font-size:16px;" class="pull-left hidden-xs showopacity glyphicon
                       glyphicon-wrench"></span></a></li>
                {%endif%}
                {%if perms.users.can_delete_user%}
                <li><a href="{% url 'users:list_user_delete' %}">{% trans "Delete Users" %}<span
                       style="font-size:16px;" class="pull-left hidden-xs showopacity glyphicon
                       glyphicon-minus-sign"></span></a></li>
                {%endif%}
                {%if perms.users.can_see_logging%}
                <li><a href="{% url 'users:logging_list' %}">{% trans "Logging Users" %}<span
                       style="font-size:16px;" class="pull-left hidden-xs showopacity glyphicon
                       glyphicon-info-sign"></span></a></li>
                {%endif%}
            </ul>
            </li>
        </ul>
    </div>

    <!-- Page to show -->
    <div id="page-content-wrapper">
        <div class="container-fluid">
            {% if messages %}
            <div class="row">
                <div class="col-md-4 col-md-offset-8">
                    {% for message in messages %}
                    <p{% if message.tags == "success" %} class= "alert alert-success"{% endif %}>{{ message }}</p>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
            {% block dashboard_content %}
            <p><strong>{% trans "User" %}</strong>: {{ request.user.username}}</p>
            <p><strong>{% trans "E-mail" %}</strong>: {{ request.user.email }}</p>
            <a type="button"  class="btn btn-success" href="http://localhost:3000/accounts/self_edit/">{% trans "Edit my Profile"%}</a>
            <a type="button"  class="btn btn-success" href="http://localhost:3000/accounts/change_password/">{% trans "Edit my Password"%}</a>
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

<script>
// Enable pusher logging - don't include this in

src/users/templates/users/delete_user.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
{% endblock %}
<title>{% trans "Delete  Users" %}</title>
{% block body %}

<div class="flex-align"><!-- começa o flex -->
  <div class="container span7 text-center col-md-4 col-md-offset-3" style="margin: 0 auto;float: none; border: 3px solid red">
    <div class="row">
      <h1>{% trans "Delete users" %}</h1>
      <p2>{{info}}</p2>

      <h1> </h1>
      <form class="col-md-6 configdiv" action="delete" method="post">
        <p2>{{falha}}</p2>

        {% csrf_token %}

      </div>
      <button type="submit" onclick="return confirm('Voce tem certeza ?')" class="btn btn-danger" href="{% url 'users:list_user_delete' %}" style="width: 250px; height: 50px">{% trans "Delete" %}</button>
      <h1> </h1>
      <p><a class="btn btn-primary" href="{% url 'users:list_user_delete' %}" role="button" style="width: 250px; height: 50px">{% trans "Cancel" %}</a></p>
    </form>
  </div>
</div>
</div><!-- termina o flex -->

{% endblock %}
{% block login %}
<form class="navbar-form navbar-right" action="login" method="post">
  <p2 color="red" >{{falha}}</p2>
  {% csrf_token %}
  <div class="form-group">
    <input type="password" name ="Password" placeholder="Password" class="form-control">
  </div>
  <button type="submit" class="btn btn-success">{% trans "Sign in" %}</button>
</form>
{% endblock %}

src/users/templates/users/edit_user.html
{% extends 'users/dashboard.html' %}
{% load i18n %}

{% block title %}
<title>{% trans "Edit User" %}</title>
{% endblock %}

{% block dashboard_content %}
<div class="jumbotron">
  <div class="container">
    <div class="wrapper">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">

          <h1>{% trans "Edit user "%}</h1>

          <div class="confirmation">
            <p2>{{info}}</p2>
          </div>

          <h1> </h1>
          <form class="configdiv" action="register" method="post">
            <p2>{{falha}}</p2>
            {% csrf_token %}
            <div class="form-group">
              <input type="text" name= "first_name" value="{{user.first_name}}" class="form-control">
            </div>
            <div class="form-group">
              <input type="text" name= "last_name" value="{{user.last_name}}" class="form-control">
            </div>
            <div class="form-group">
              <input type="text" name= "email" value="{{user.email}}" class="form-control">
            </div>
            <p1>{% trans "User type:" %}</p1>
            <div class="form-group">
              <label class="radio-inline">
                <input type="radio" name="user_type" id="inlineRadio1" value="common"> {% trans "Commun User" %}
              </label>
              <label class="radio-inline">
                <input type="radio" name="user_type" id="inlineRadio2" value="admin">{% trans " Admin" %}
              </label>
            </div>
            <p1>{% trans "Access level:" %}</p1>
            <div class="form-group">
              <div class="checkbox">
                <label class="checkbox-inline checkbox-success">
                  <input type="checkbox" id="permissions_checkbox1" name="can_generate" {{can_generate}} > {% trans "Generate Reports" %}
                </label>
              </div>
              <div class="checkbox">
                <label class="checkbox-inline checkbox-success">
                  <input type="checkbox" id="permissions_checkbox2" name="view_transductors" {{view_transductors}}> {% trans "Manage Transductors" %}
                </label>
              </div>
              <div class="checkbox">
                <label class="checkbox-inline checkbox-success">
                  <input type="checkbox" id="permissions_checkbox3" name="edit_users" {{edit_users}} > {% trans "Edit Users" %}
                </label>
              </div>
              <div class="checkbox">
                <label class="checkbox-inline checkbox-success">
                  <input type="checkbox" id="permissions_checkbox4" name="delete_users" {{delete_users}}> {% trans "Delete Users" %}
                </label>
              </div>
              <div class="checkbox">
                <label class="checkbox-inline checkbox-success">
                  <input type="checkbox" id="permissions_checkbox5" name="see_logging" {{see_logging}} > {% trans "See Logging" %}
                </label>
              </div>
            </div>
            <button type="submit" class="btn btn-success" onclick="return confirm('Voce tem certeza ?')" >{% trans "Register" %}</button>
            <input type="hidden" name="original_email" value="{{user.email}}">
            <button type="submit" class="btn btn-success" >{% trans "Register" %}</button>
            <a class="btn btn-primary" href="{% url 'users:list_user_edit' %}" role="button">{% trans "Cancel" %}</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block login %}
<form class="navbar-form navbar-right" action="login" method="post">
  <p2 color="red" >{{falha}}</p2>
  {% csrf_token %}
  <div class="form-group">
    <input type="text" name= "Email" placeholder="Email" class="form-control">
  </div>
  <div class="form-group">
    <input type="password" name ="Password" placeholder="Password" class="form-control">
  </div>
  <button type="submit" class="btn btn-success">{% trans "Sign in" %}</button>
</form>
{% endblock %}

src/users/templates/users/home.html
<!-- Arquivo: templates/users/home.html -->
{% load i18n %}

<p>OBRIGADO POR UTILIZAR O SME{% if user.is_authenticated %}{{ user.first_name }}{% else %}...{% endif %}</p>

{% if user.is_authenticated %}
{% block body %}
<div class="jumbotron">
  <div class="container">
    <h1>{% trans "Welcome!" %}</h1>
    <p>{% trans "SME - UnB is a web platform to monitor measurements from energy transductors" %}.</p>
    <p><a class="btn btn-primary btn-lg" href="https://gitlab.com/brenddongontijo/SME-UnB" role="button">{% trans "Learn more" %} &raquo;</a></p>
  </div>
</div>
{% endblock %}
<p><a href="{% url 'users:logout' %}">{% trans "Logout" %}</a>.</p>
<p><a href="{% url 'users:dashboard' %}">{% trans "Dashboard" %}</a>.</p>
{% else %}
<meta http-equiv="refresh" content=1;url="/">
<p>{% trans "Redirecting..." %}</p>
{% endif %}

src/users/templates/users/list_user_delete.html
{% extends 'users/dashboard.html' %}
{% load i18n %}

{% block dashboard_content %}
<div class="margin">
  <h1 class="text-center">{% trans "List of Registered Users:" %}</h>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="margin">
        <table class ="table table-bordered">
          <tr>
            <th>{% trans "First Name" %}</th>
            <th>{% trans "Last Name" %}</th>
            <th>{% trans "Email" %}</th>
            <th>{% trans "Delete" %}</th>
          </tr>
          {% for user in users %}
          <tr>
            {% if user.email != request.user.email %}
            <td>{{user.first_name}}</td>
            <td>{{user.last_name}}</td>
            <td>{{user.username}}</td>
            <td><a  class="glyphicon glyphicon-trash" href="{% url 'users:delete_user' user.id %}"></a></td>
          </tr>
          {% endif %}
          {% endfor %}
        </table>
      </div>

    </div>
  </div>

  {% endblock %}

src/users/templates/users/list_user_edit.html
{% extends 'users/dashboard.html' %}
{% load i18n %}

{% block dashboard_content %}


<div class="margin">
  <h1 class="text-center">{% trans "List of registered Users:" %}</h>
  </div>

  <br />
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="margin">

        <table class ="table table-bordered">
          <tr>
              <th>{% trans "First Name" %}</th>
              <th>{% trans "Last Name" %}</th>
              <th>{% trans "Email" %}</th>
              <th>{% trans "Edit" %}</th>
          </tr>
          {% for user in users %}
            {% if user.id != request.user.id %}
              <tr>
                <td>{{user.first_name}}</td>
                <td>{{user.last_name}}</td>
                <td>{{user.username}}</td>
                <td><a  class="glyphicon glyphicon-pencil" href="{% url 'users:edit_user' user.id %}"></a></td>
              </tr>
            {% endif %}
          {% endfor %}
          </tab
        </div>
      </div>
    </div>


    {% endblock %}

src/users/templates/users/logging_list.html
{% extends 'users/dashboard.html' %}
{% load i18n %}

{% block dashboard_content %}


<div class="margin">
  <h1 class="text-center">{% trans "List of Logging:" %}</h>
  </div>

  <br />
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="margin">

        <table class ="table table-bordered">

          <tr>
            <td>{{logging|linebreaks}}</td>            
          </tr>


          </tab
        </div>
      </div>
    </div>


    {% endblock %}

src/users/templates/users/login.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_messages %}
{% load i18n %}

{% block title %}
    <title>{% trans "SME - Login" %}</title>
{% endblock %}
  {% block body %}
  <div class="container">
    <div class="col-md-4 col-md-offset-4">

      <form class="form-signin" method="POST" action="{% url "users:login"%}">
        {% csrf_token %}
        <h2 class="form-signin-heading text-center">{% trans "Log in" %}</h2>
        <div class="form-group">
          <label for="inputEmail" class="sr-only">{% trans "Email address" %}</label>
          <input type="user" id="inputUsername" name="username" class="form-control" placeholder="Email" required autofocus>
        </div>
        <div class="form-group">
          <label for="inputPassword" class="sr-only">{% trans "Password" %}</label>
          <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
        </div>
        <div class="form-group">
            <a href="{% url "retrieve:forgot" %}">Esqueci a senha</a>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Log in" %}</button>
      </form>
    </div>
  </div>
  {% endblock %}