src/SME_UnB/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^transductor/', include('transductor.urls',
                                  namespace="transductor")),
    url(r'^accounts/', include('users.urls', namespace="users")),
    url(r'^reports/', include('report.urls', namespace="report")),
    url(r'^retrieve_password/', include('retrieve_password.urls', namespace="retrieve")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

src/transductor/urls.py
from django.conf.urls import url

from . import views

app_name = 'transductor'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new$', views.new, name='new'),
    url(r'^(?P<transductor_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<transductor_id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<transductor_id>[0-9]+)/delete/$', views.delete, name='delete'),
    url(r'^model$', views.model_index, name='model_index'),
]

src/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^dashboard/$', views.dashboard, name="dashboard"),
    url(r'^$', views.show_login, name="home"),
    url(r'^login/$', views.show_login, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^register/', views.register, name="register"),
    url(r'^list_user_edit/', views.list_user_edit, name="list_user_edit"),
    url(r'^list_user_delete/',
        views.list_user_delete,
        name="list_user_delete"),
    url(r'^edit_user/(?P<user_id>[0-9]+)/',
        views.edit_user,
        name="edit_user"),
    url(r'^delete_user/(?P<user_id>[0-9]+)/',
        views.delete_user,
        name="delete_user"),
    url(r'^self_edit/', views.self_edit_user, name="self_edit_user"),
    url(r'^logging_list/', views.logging_list, name="logging_list"),
    url(r'^change_password/', views.change_password, name="change_password"),
]

SME_UnB/transductor/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.validators import RegexValidator
from django.contrib.postgres.fields import ArrayField


class TransductorModel(models.Model):
    name = models.CharField(max_length=50, unique=True)
    internet_protocol = models.CharField(max_length=50)
    serial_protocol = models.CharField(max_length=50)
    register_addresses = ArrayField(models.IntegerField())

    def __str__(self):
        return self.name


class Transductor(models.Model):
    model = models.ForeignKey(TransductorModel)
    serie_number = models.IntegerField(default=None)
    ip_address = models.CharField(max_length=15, unique=True, validators=[
        RegexValidator(
            regex='^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$',
            message='Incorrect IP address format',
            code='invalid_ip_address'
        ),
    ])
    description = models.TextField(max_length=150)
    creation_date = models.DateTimeField('date published')

    class Meta:
        abstract = True
        permissions = (
            ("can_view_transductors", "Can view Transductors Page"),
        )


class EnergyTransductor(Transductor):

    def __str__(self):
        return self.description


class Measurements(models.Model):

    collection_date = models.DateTimeField('date published')

    class Meta:
        abstract = True


class EnergyMeasurements(Measurements):

    transductor = models.ForeignKey(EnergyTransductor,
                                    on_delete=models.CASCADE)

    voltage_a = models.FloatField(default=None)
    voltage_b = models.FloatField(default=None)
    voltage_c = models.FloatField(default=None)

    current_a = models.FloatField(default=None)
    current_b = models.FloatField(default=None)
    current_c = models.FloatField(default=None)

    active_power_a = models.FloatField(default=None)
    active_power_b = models.FloatField(default=None)
    active_power_c = models.FloatField(default=None)

    reactive_power_a = models.FloatField(default=None)
    reactive_power_b = models.FloatField(default=None)
    reactive_power_c = models.FloatField(default=None)

    apparent_power_a = models.FloatField(default=None)
    apparent_power_b = models.FloatField(default=None)
    apparent_power_c = models.FloatField(default=None)

    def __str__(self):
        return '%s' % self.collection_date

    def calculate_total_active_power(self):
        return (self.active_power_a +
                self.active_power_b +
                self.active_power_c)

    def calculate_total_reactive_power(self):
        return (self.reactive_power_a +
                self.reactive_power_b +
                self.reactive_power_c)

    def calculate_total_apparent_power(self):
        ap_phase_a = self.apparent_power_a
        ap_phase_b = self.apparent_power_b
        ap_phase_c = self.apparent_power_c

        ap_total = (ap_phase_a + ap_phase_b + ap_phase_c)

        return ap_total

src/transductor/forms.py
from django import forms
from .models import EnergyTransductor, TransductorModel


class EnergyForm(forms.ModelForm):
    transductor_model = forms.ModelChoiceField(queryset=TransductorModel.objects.all(), required=True, initial=0)

    class Meta:
        model = EnergyTransductor
        fields = ('serie_number', 'ip_address', 'description',)

class DeleteEnergyForm(forms.ModelForm):
    class Meta:
        model = EnergyTransductor
        fields = []

src/transductor/views.py
from .models import EnergyTransductor, TransductorModel
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from .forms import EnergyForm, DeleteEnergyForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required


def index(request):
    template_name = 'transductor/index.html'
    transductors_list = EnergyTransductor.objects.all()

    return render(request, template_name,
                  {'transductors_list': transductors_list})


@login_required
def detail(request, transductor_id):
    template_name = 'transductor/detail.html'
    transductor = get_object_or_404(EnergyTransductor, pk=transductor_id)

    measurements = EnergyTransductor.objects \
        .get(id=transductor_id).energymeasurements_set.all()
    paginator = Paginator(measurements, 4)
    page = request.GET.get('page')

    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    return render(request, template_name,
                  {'measurements': data, 'transductor': transductor})


@login_required
def new(request):
    if request.POST:
        form = EnergyForm(request.POST)

        if form.is_valid():
            transductor = EnergyTransductor()
            transductor.serie_number = form.cleaned_data['serie_number']
            transductor.ip_address = form.cleaned_data['ip_address']
            transductor.description = form.cleaned_data['description']
            transductor.model = form.cleaned_data['transductor_model']
            transductor.creation_date = timezone.now()

            try:
                transductor.save()
            except ValidationError, err:
                errors = '; '.join(err.messages)
                return render(request, 'transductor/new.html', {'form': form, 'errors': errors})

            return redirect('transductor:detail', transductor_id=transductor.id)
    else:
        form = EnergyForm()

    return render(request, 'transductor/new.html', {'form': form})



@login_required
def edit(request, transductor_id):
    transductor = get_object_or_404(EnergyTransductor, pk=transductor_id)

    if request.POST:
        form = EnergyForm(request.POST, instance=transductor, initial={'model': transductor.model})
        if form.has_changed() and form.is_valid():
            for data in form.changed_data:
                setattr(form.instance, data, form.cleaned_data[data])

        if form.is_valid():
            form.save()
            return redirect('transductor:index')
        else:
            # Add no changes error
            pass
    else:
        form = EnergyForm(instance=transductor, initial={'model': transductor.model})

    return render(request, 'transductor/new.html', {'form': form})


@login_required
def delete(request, transductor_id):
    transductor = get_object_or_404(EnergyTransductor, pk=transductor_id)

    if request.POST:
        form = DeleteEnergyForm(request.POST, instance=transductor)

        if form.is_valid():
            transductor.delete()

    return HttpResponseRedirect(reverse('transductor:index'))


def model_index(request):
    template_name = 'transductor/model_index.html'
    transductors_models = TransductorModel.objects.all()

    return render(request, template_name,
                  {'transductors_models': transductors_models})

src/transductor/templates/transductor/detail.html
{% extends 'base.html' %}

{% block title %}
  <title>{% trans "Measurements Record "%}</title>
{% endblock %}

{% block body %}
  <div class="page-header">
    <div class="starter-template">
      <h1>{{transductor.description.title}}</h1>
    </div>
  </div>
{% if measurements %}
  <div class="col-md-6" style="text-align: center">
  {% for measurement in measurements %}
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">{{ measurement.collection_date }}</h3>
      </div>

      <table class="table table-striped">
      <thead>
        <tr>
          <th></th>
          <th>{% trans "Phase A"%}</th>
          <th>{% trans "Phase B"%}</th>
          <th>{% trans "Phase C"%}</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Voltage</td>
          <td>{{ measurement.voltage_a }}</td>
          <td>{{ measurement.voltage_b }}</td>
          <td>{{ measurement.voltage_c }}</td>
        </tr>
        <tr>
          <td>Current</td>
          <td>{{ measurement.current_a }}</td>
          <td>{{ measurement.current_b }}</td>
          <td>{{ measurement.current_c }}</td>
        </tr>
        <tr>
          <td>Active Power</td>
          <td>{{ measurement.active_power_a }}</td>
          <td>{{ measurement.active_power_b }}</td>
          <td>{{ measurement.active_power_c }}</td>
          <td>{{ measurement.calculate_total_active_power }}</td>
        </tr>
        <tr>
          <td>Reactive Power</td>
          <td>{{ measurement.reactive_power_a }}</td>
          <td>{{ measurement.reactive_power_b }}</td>
          <td>{{ measurement.reactive_power_c }}</td>
          <td>{{ measurement.calculate_total_reactive_power }}</td>
        </tr>
        <tr>
          <td>Apparent Power</td>
          <td>{{ measurement.apparent_power_a }}</td>
          <td>{{ measurement.apparent_power_b }}</td>
          <td>{{ measurement.apparent_power_c }}</td>
          <td>{{ measurement.calculate_total_apparent_power }}</td>
        </tr>
      </tbody>
    </table>
    </div>
  {% endfor %}
    <div class="pagination">
      <span class="step-links">
        {% if measurement_list.has_previous %}
          <a href="?page={{ measurement_list.previous_page_number }}">{% trans "Previus" %}</a>
        {% endif %}

        <span class="current">
          Page {{ measurement_list.number }} of {{ measurement_list.paginator.num_pages }}
        </span>

        {% if measurement_list.has_next %}
          <a href="?page={{ measurement_list.next_page_number }}">{% trans "Next" %}</a>
        {% endif %}
      </span>
    </div>
  </div>
{% else %}
  <div class="container">
    <div class="starter-template">
      <h1>{% trans "No measurement avaiable"%}</h1>
    </div>
  </div>
{% endif %}
{% endblock %}

src/transductor/templates/transductor/index.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    <title>Transductors</title>
{% endblock %}

{% block body %}
<div class="col-md-6">
  <table class="table table-striped">
    {% if transductors_list %}
      <p><a href="{% url 'transductor:new' %}" class="btn btn-primary">{% trans "Create Transductor"%}</a></p>
      <thead>
        <tr>
          <th>#</th>
          <th>{% trans "Description"%}</th>
          <th>{% trans "IP Address"%}</th>
          <th>{% trans "Serie Number"%}</th>
          <th>{% trans "Options"%}</th>
        </tr>
      </thead>

      {% for transductor in transductors_list %}
      <tbody>
        <tr>
          <td>{{transductor.id}}</td>
          <td><a href="{% url 'transductor:detail' transductor.id %}">{{transductor.description}}</a></td>
          <td>{{transductor.ip_address}}</td>
          <td>{{transductor.serie_number}}</td>
          <td>
            <a title="Click here to edit" href="{% url 'transductor:edit' transductor_id=transductor.id %}"><span class="glyphicon glyphicon-pencil"></span></a>

            <form id="deleteform" action="{% url 'transductor:delete' transductor_id=transductor.id %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="delete" value="value">
              <button onclick="return confirm('Are you sure?')"><span class="glyphicon glyphicon-trash"></button>
            </form>
          </td>
        </tr>
      </tbody>
      {% endfor %}
    {% else %}
      <div class="container">
        <div class="starter-template">
          <h1>{% trans "No Registered Transducer"%}</h1>
          <p class="lead">{% trans "To create a new transductor click "%}"<a href="{% url 'transductor:new' %}" >here</a></p>
        </div>
      </div>
    {% endif %}
</table>
</div>
{% endblock %}

src/transductor/templates/transductor/model_index.html
{% extends 'base.html' %}

{% block title %}
    <title>{% trans "Transductors Models"%}</title>
{% endblock %}

{% block body %}
<div class="col-md-6">
  <table class="table table-striped">
    {% if transductors_models %}
      <thead>
        <th>{% trans "Name"%}</th>
        <th>{% trans "Internet Protocol"%}</th>
        <th>{% trans "Serial Protocol"%}</th>
      </thead>
      {% for model in transductors_models %}
        <tbody>
          <tr>
            <td>{{model.name}}</td>
            <td>{{model.transport_protocol}}</td>
            <td>{{model.serial_protocol}}</td>
          </tr>
        </tbody>
      {% endfor %}
    {% else %}
      <div class="container">
        <div class="starter-template">
          <h1>{% trans "Nothing Registered"%}</h1>
        </div>
      </div>
    {% endif %}
  </table>
</div>
{% endblock %}

src/transductor/templates/transductor/new.html
{% extends 'base.html' %}

{% block title %}
    <title>{% trans "New Transductor"%}</title>
{% endblock %}

{% block body %}
    <h1>{% trans "New Transductor"%}</h1>

    {% if errors %}
        <p style="color: #ff0000;">{{errors}}</p>
    {% endif %}

    <form method="post" class="post-form">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="save btn btn-default">{% trans "Save"%}</button>
        <a href="{% url 'transductor:index' %}" class="save btn btn-default">{% trans "Cancel"%}</button>
    </form>
{% endblock %}